version: "3"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - qdrant
      - redis
    environment:
      - QDRANT_URL=http://qdrant:6333
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./input_data:/app/input_data
    stdin_open: true
    tty: true
    command: ["python", "main.py"]
  worker:
    build: .
    depends_on:
      - qdrant
      - redis
    environment:
      - QDRANT_URL=http://qdrant:6333
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: ["celery", "-A", "async_tasks.tasks", "worker", "--loglevel=info"]
volumes:
  qdrant_data:
