version: "3"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  app:
    build: .
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./input_data:/app/input_data
    stdin_open: true
    tty: true
    command: ["python", "main.py"]
volumes:
  qdrant_data:
