apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-heitaa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rag-heitaa
  template:
    metadata:
      labels:
        app: rag-heitaa
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: QDRANT_URL
              value: http://qdrant:6333
          command: ["python","main.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: rag-heitaa
spec:
  selector:
    app: rag-heitaa
  ports:
    - port: 80
      targetPort: 8000
